### ISSUE TITLE
TOML Empty Tables

### ISSUE THREAD

**Issue by codyja** [jtyr/ansible-config_encoder_filters#10]
Hi, 
First off, thank you for this solution, it's been great!

I noticed what I think may be an issue when rendering an empty table in TOML. An empty table is apparently valid, and it's a way to enable a specific plugin in telegraf, which doesn't need any additional configuration. 

From the TOML [specs](https://github.com/toml-lang/toml#table):
`Empty tables are allowed and simply have no key/value pairs within them.`

Here is a sample YAML data structure in ansible I'd like to render into TOML:
```
telegraf_config__custom:
  inputs:
    - statsd:
        protocol: "udp"
    - diskio:
```
It should render as something like this:
```
[inputs.statsd]
protocol = "udp"

[inputs.diskio]
```

However, it actually results in this which isn't valid:
```
[inputs.statsd]
protocol = "udp"

[[inputs]]
diskio =
```
