### ISSUE TITLE
Syntax error reported by apache when all arguments are quoted.

### ISSUE THREAD

**Issue by vbotka** [jtyr/ansible-config_encoder_filters#11]
The syntax error below is reported
```
    AH00526: Syntax error on line 3 of /usr/local/etc/apache24/Includes/usr-local-www-apache-data.conf:
    AddType requires at least two arguments, a mime type followed by one or more file extensions
```

when the apache filter with the data below

```
> cat usr-local-www-apache-data.yml 
---
my_apache_dir:
  content:
    - sections:
        - name: Directory
          param: "/usr/local/www/apache24/data/"
          content:
            - options:
                - DirectoryIndex: index.php index.html index.htm
                - AddType: application/x-httpd-php .php
                - AddType: application/x-httpd-php-source .phps
                - Options: Indexes FollowSymLinks
                - AllowOverride: All
                - Require: all granted
...
```
creates this *Directory* section:

```
# cat usr-local-www-apache-data.conf
<Directory /usr/local/www/apache24/data/>
  DirectoryIndex "index.php index.html index.htm"
  AddType "application/x-httpd-php .php"
  AddType "application/x-httpd-php-source .phps"
  Options "Indexes FollowSymLinks"
  AllowOverride All
  Require "all granted"
</Directory>
```
Correct syntax is:

```
# cat usr-local-www-apache-data.conf
<Directory /usr/local/www/apache24/data/>
  DirectoryIndex index.php index.html index.htm
  AddType application/x-httpd-php .php
  AddType application/x-httpd-php-source .phps
  Options Indexes FollowSymLinks
  AllowOverride All
  Require all granted
</Directory>
```
Simple fix is to ommit the _escape function:

```
diff --git a/filter_plugins/config_encoders.py b/filter_plugins/config_encoders.py
index 93b23a2..fa5e1fb 100644
--- a/filter_plugins/config_encoders.py
+++ b/filter_plugins/config_encoders.py
@@ -214,7 +214,7 @@ def encode_apache(
                     "\r" in data or
                     data == ""):

-                rv += '"%s"' % _escape(data)
+                rv += data
             else:
                 rv += data
```

I'm not sure if the removal of the_escape function won't cause other syntax errors. (WIP)

**Comment by jtyr** [comment]
You are using incorrect syntax. Please try this:

```yaml
my_apache_dir:
  content:
    - sections:
        - name: Directory
          param: /usr/local/www/apache24/data/
          content:
            - options:
                - DirectoryIndex: index.php index.html index.htm
                - AddType:
                    - application/x-httpd-php
                    - .php
                - AddType:
                    - application/x-httpd-php-source
                    - .phps
                - Options: Indexes FollowSymLinks
                - AllowOverride: All
                - Require: all granted
```

**Comment by vbotka** [comment]
Thank you very much for the quick explanation. Other parameters must have been passed as lists too.
```
my_apache_dir:
  content:
    - sections:
        - name: Directory
          param: /usr/local/www/apache24/data/
          content:
            - options:
                - DirectoryIndex: index.php index.html index.htm
                - AddType:
                    - application/x-httpd-php
                    - .php
                - AddType:
                    - application/x-httpd-php-source
                    - .phps
                - Options:
                    - Indexes
                    - FollowSymLinks
                - AllowOverride: All
                - Require:
                    - all
                    - granted
```
There were syntax errors:
- Illegal option Indexes FollowSymLinks
- Unknown Authz provider: all granted

There is no problem with quoting *DirectoryIndex* parameters

```
<Directory /usr/local/www/apache24/data/>
  DirectoryIndex "index.php index.html index.htm"
  AddType application/x-httpd-php .php
  AddType application/x-httpd-php-source .phps
  Options Indexes FollowSymLinks
  AllowOverride All
  Require all granted
</Directory>
```
