### ISSUE TITLE
Output file not sorted?

### ISSUE THREAD

**Issue by dR3b** [jtyr/ansible-config_encoder_filters#13]
I would like to create a configuration file for "sway". Unfortunately the output is always sorted. But "sway" does not like that. 
```yml
---
sway:
  set:
    - $mod Mod4
  bindsym:
    - $mod+Return exec $term
    - $mod+d kill
```
__output:__

```bash
bindsym $mod+Return exec $term
bindsym $mod+d kill
set $mod Mod4
```
How can I prevent this?
Thanks.

**Comment by jtyr** [comment]
Please can you share your filter definition?

**Comment by dR3b** [comment]
So far only this one:
```
{{ sway | encode_ini(delimiter=" ")}}
```

**Comment by jtyr** [comment]
The `encode_ini` filter always sorts the keys because the data is a `dict`. You have to use other filter which expects the data to be a `list`, for example the `encode_haproxy` filter:

```yaml
# site.yaml
- hosts: all
  connection: local
  gather_facts: no
  vars:
    sway:
      - set $mod Mod4
      - bindsym $mod+Return exec $term
      - bindsym $mod+d kill
  tasks:
    - template:
        src: sway.j2
        dest: /tmp/test.txt
```



```yaml
# sway.j2
{{ sway | encode_haproxy(indent="")}}
```
