### ISSUE TITLE
encode_apache filter and sub sections

### ISSUE THREAD

**Issue by pirzyk** [jtyr/ansible-config_encoder_filters#17]
I'm trying to create a virtual host configuration that has sub sections, but the `encode_apache` filter does not seem to recurse properly to include the `Directory` or `Location` sections in the output.  I suspect I have this parameterized incorrectly.
```
my_apache_vhost:
  content:
    - sections:
      - name: VirtualHost
        param: "{{ ansible_fqdn }}:443"
        content:
          - sections:
            - name: Directory
              param: "{{ apache_documentroot }}"
              content:
                - Options:
                  - '+FollowSymLinks'
                  - '-Indexes'
                - AllowOverride: none
                - Require:
                  - all
                  - granted
          - sections:
            - name: Location
              param: /wordpress
              content:
                - Require: "ip {{ pf_my_network | join('\nRequire ip ') }}"
          - options:
            - ServerName: "{{ ansible_fqdn }}"
            - DocumentRoot: "/usr/local/www/html-{{ ansible_fqdn }}"
            - Alias:
              - /wordpress
              - /usr/local/www/wordpress
```
I get this in the rendering:
```
<VirtualHost HOSTNAME:443>
  ServerName HOSTNAME
  DocumentRoot /usr/local/www/html-HOSTNAME
  Alias /wordpress /usr/local/www/wordpress
</VirtualHost>
```
I expect the following:
```
<VirtualHost HOSTNAME:443>
  ServerName HOSTNAME
  DocumentRoot /usr/local/www/html-HOSTNAME
  Alias /wordpress /usr/local/www/wordpress
  <Directory "/usr/local/www/html-HOSTNAME">
    Options +FollowSymLinks -Indexes
    AllowOverride none
    Require all granted
  </Directory>
  <Location /wordpress>
    Require ip 192.168.0.0/16
    Require ip 172.16.0.0/12
    Require ip 10.0.0.0/8
  </Location> 
</VirtualHost>
```

I'm using `ansible [core 2.11.4]`, `python version = 3.9.7`, and `jinja version = 3.0.1`

**Comment by jtyr** [comment]
You forgot to use `-options:` in your inner sections. I have also fixed your `Required ip` block:

```yaml
my_apache_vhost:
  content:
    - sections:
      - name: VirtualHost
        param: "{{ ansible_fqdn }}:443"
        content:
          - sections:
            - name: Directory
              param: "{{ apache_documentroot }}"
              content:
                - options:
                    - Options:
                      - '+FollowSymLinks'
                      - '-Indexes'
                    - AllowOverride: none
                    - Require:
                      - all
                      - granted
            - name: Location
              param: /wordpress
              content:
                - options:
                  - "# trick": "\n{{ ['    Required ip '] | product(pf_my_network) | map('join') | list | join('\n') }}\n    #"
          - options:
            - ServerName: "{{ ansible_fqdn }}"
            - DocumentRoot: /usr/local/www/html-{{ ansible_fqdn }}
            - Alias:
              - /wordpress
              - /usr/local/www/wordpress
```
