### ISSUE TITLE
how can i create this erlang config:

### ISSUE THREAD

**Issue by Raffaello** [jtyr/ansible-config_encoder_filters#2]
`  {cluster_nodes, {['rabbit@dev-c1n01-rabbitmq', 'rabbit@dev-c1n02-rabbitmq', 'rabbit@dev-c1n03-rabbitmq'], disc}}`

i am not able to create the `{...}` value with a list and another value:

is it possible to create that entry?

**Comment by jtyr** [comment]
Which encoder are you using? `encode_erlang`?

**Comment by jtyr** [comment]
Currently it is only possible to create `{a, [b, c]}` but not `{a, {[b, c]}}`. The reason is that the current implementation depends on valid YAML structure where it's not possible to have a map where the key is a list. Please feel free to create a PR improving the current solution.

**Comment by jtyr** [comment]
Are you sure you using the right configuration? All the configurations mentioned on the [clustering site](https://www.rabbitmq.com/clustering.html) are able to construct with the Erlang encoder.

**Comment by Raffaello** [comment]
`cluster_nodes`

> Set this to cause clustering to happen automatically when a node starts for the very first time. The first element of the tuple is the nodes that the node will try to cluster to. The second element is either disc or ram and determines the node type.
> 
> Default: {[], disc}

ref: https://www.rabbitmq.com/configure.html#configuration-file

---

so it seems it would be something like i have already reported:

```
{cluster_nodes, {['node1', 'node2'], disc}}
```

**Comment by jtyr** [comment]
I'm afraid that this data structure is currently not supported ;o(

**Comment by Raffaello** [comment]
what about if we design a sort of special char(s) to make that kind of structures, something like this:
```yaml
'{':
  - :node1
  - :node2
'disc}': ~

```
the special case it will start with `'{'` key and then followed by a list after the list it be the 2nd value, or the last element of the list could be too:
```yaml
'{':
  - :node1
  - :node2
  - disc

```
what do you think? probably it would go outside the scope of the general encoder filter to address a special erlang config case. not sure.

**Comment by jtyr** [comment]
Would this workaround work for you?

```
---

- hosts: all
  gather_facts: no
  connection: local
  vars:
    xxx:
      cluster_nodes:
        "['node1', 'node2']": disc
  roles:
    - config_encoder_filters
  tasks:
    - copy:
        dest: /tmp/test.cfg
        content: >
          {{ xxx | encode_erlang }}
```

Producing this output:

```
$ cat /tmp/test.cfg

{cluster_nodes,
  {['node1', 'node2'], "disc"}}
```

**Comment by jtyr** [comment]
If that doesn't work, I will implement a special construct like this:

```
my_config:
  ::
    -
      - node1
      - node2
    - disc
```

**Comment by jtyr** [comment]
@Raffaello, I have just pushed an update to the filters which should cover the construction from the previous comment. Please test it and let me know if that works for you.

**Comment by Raffaello** [comment]
i wrote the snippet like this:
```
cluster_nodes:
          ::
            -
              - rabbit@rabbitmq-1
              - rabbit@rabbitmq-2
            - :disc
```

it gave me syntax error while loading YAML.

**Comment by jtyr** [comment]
Please check the [test file](https://github.com/jtyr/ansible-config_encoder_filters/blob/master/tests/files/encode_erlang_mixed.in) for the right syntax. The test passes just fine:

```
$ python2 -m unittest tests.test_config_encoders.TestErlang.test_mixed
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
```

**Comment by Raffaello** [comment]
ok i have tested fetching the last from the master. The yaml syntax is ok.
but i have an error on the Jinja2 template here:

```
{{ rabbitmq_config | encode_erlang(convert_bools=true, convert_nums=true) }}
```
error:
```
fatal: [rabbitmq-1]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleError: Unexpected templating type error occurred on (\n\n{{ rabbitmq_config | encode_erlang(convert_bools=true, convert_nums=true) }}\n): 'NoneType' object is not iterable"}
```

my yaml file

```yml
   rabbitmq_config:
      - rabbit:
        - cluster_nodes:
          ::
            -
              - node1
              - node2
            - :disc

```

any clues? 
thanks

**Comment by jtyr** [comment]
You have an error in the indentation:

```
   rabbitmq_config:
      - rabbit:
        - cluster_nodes:
            ::
              -
                - node1
                - node2
              - :disc
```
