### ISSUE TITLE
Top-Level Interpolation Error

### ISSUE THREAD

**Issue by con5cience** [jtyr/ansible-config_encoder_filters#3]
This issue is occurring when I'm using your `ansible-bind` role but this appears to be more relevant to the `config_encoder_filters` offering:

```
  - zone "{{ env | lower }}.fnord.com":
    - type master
    - file "{{ env | lower }}.fnord.com.db"
    - allow-update { key "fnord.com"; }
```

Produces the following configuration in `/etc/named.conf` where `env` is already defined as `"production"`:

```
zone "{{ env | lower }}.fnord.com" {
  type master;
  file "production.fnord.com.db";
  allow-update { key "fnord.com"; };
};
```

I'd like to get that top-level variable resolving correctly. Any advice?

**Comment by jtyr** [comment]
It is not an issue in the encoders. It's a feature inside Ansible itself. Have a look [here](https://github.com/ansible/ansible/pull/19664) for more details.

**Comment by con5cience** [comment]
"Feature". Thanks! :)

**Comment by con5cience** [comment]
Sorry, perhaps I don't understand the implications of the PR you linked. I've tried single-quoting the variable (and even removing the `lower` Jinja filter) and it's still resolving as raw text. Can you help me figure out what's needed here to get this working?

**Comment by jtyr** [comment]
yeah, it looks like the workaround only works with maps but not with arrays:

```
$ cat site.yaml
---

- hosts: all
  connection: local
  gather_facts: no
  vars:
    env: Prod
    config1: >
      {
        "z {{ env }} s": {
            "{{ env }}": "mygw",
            "network": "myvlan"
        }
      }
    config2: >
      {
        "z {{ env }} s": [
            "{{ env }}": "mygw",
            "network": "myvlan"
        ]
      }
  tasks:
    - name: This works
      copy:
        content: "{{ config1 }}"
        dest: /tmp/test1.txt
    - name: This does not
      copy:
        content: "{{ config2 }}"
        dest: /tmp/test2.txt
$ ansible-playbook -i localhost, --diff site.yaml 

PLAY [all] ***********************************************************************************************************

TASK [This works] ****************************************************************************************************
--- before
+++ after: /tmp/tmpw7RaaT
@@ -0,0 +1 @@
+{"z Prod s": {"Prod": "mygw", "network": "myvlan"}}
\ No newline at end of file

changed: [localhost]

TASK [This does not] *************************************************************************************************
--- before
+++ after: /tmp/tmpswlpaC
@@ -0,0 +1,6 @@
+{
+  "z Prod s": [
+      "Prod": "mygw",
+      "network": "myvlan"
+  ]
+}

changed: [localhost]

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0
```

**Comment by con5cience** [comment]
Ok, so it's not gonna happen. I can work around that. Thanks for the test output.

**Comment by jtyr** [comment]
Actually, the second case above is not valid YAML. It works like this:

```
$ cat site.yaml
---

- hosts: all
  connection: local
  gather_facts: no
  vars:
    env: Prod
    config: |
      [
        { "zone {{ env | lower }}.fnord.com": [
            'type master',
            'file "{{ env | lower }}.fnord.com.db"',
            'allow-update { key "fnord.com"; }'
        ]}
      ]
  roles:
    - config_encoder_filters
  tasks:
    - copy:
        content: "{{ config | encode_nginx(block_semicolon=true) }}"
        dest: /tmp/test.txt
$ ansible-playbook -i localhost, --diff site.yaml 

PLAY [all] ***********************************************************************************************************

TASK [copy] **********************************************************************************************************
--- before
+++ after: /tmp/tmprSDfTq
@@ -0,0 +1,5 @@
+zone prod.fnord.com {
+  type master;
+  file "prod.fnord.com.db";
+  allow-update { key "fnord.com"; };
+};

changed: [localhost]

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

**Comment by con5cience** [comment]
How do I reformat how `bind_config` is declared in order to make this work with your module then? Something like this?
```
bind_config: |
  [ {
    options: [
      'listen-on port 53: [ 0.0.0.0 ]',
      'directory "/var/named"'
    ] }, {
    zone "{{ env }}.fnord.com": [
      'type master',
      'file "{{ env }}.fnord.com.db"',
      'allow-update { key "fnord.com"; }'
    ] },
 ]
```

**Comment by con5cience** [comment]
I got it all working as expected by doing this:
```
bind_base_config:
  - options:
    - directory "/var/named"
    - dump-file "/var/named/data/cache_dump.db"
    - statistics-file "/var/named/data/named_stats.txt"
    - memstatistics-file "/var/named/data/named_mem_stats.txt"
    - recursion yes
    - dnssec-enable no
    - dnssec-validation no
    - bindkeys-file "/etc/named.iscdlv.key"
  - logging:
    - channel default_debug:
      - file "data/named.run"
      - severity dynamic
  - key "fnord.com":
    - algorithm hmac-md5
    - secret "{{ ddns_key }}"

bind_zone_config: |
  [
  { 'zone "."': [ 'type hint', 'file "named.ca"' ] },
  { 'zone "{{ env }}.fnord.com"': [ 'type master', 'file "{{ env }}.fnord.com.db"', 'allow-update { key "fnord.com"; }' ] }
  ]

bind_includes:
  - include "/etc/named.rfc1912.zones"
  - include "/etc/named.root.key"

bind_config: "{{ bind_base_config + bind_zone_config + bind_includes }}"
```
What a nightmare.
