### ISSUE TITLE
Escaping characters question

### ISSUE THREAD

**Issue by pedrojflores** [jtyr/ansible-config_encoder_filters#4]
Regarding the logstash config encoder filter

The following grok block:

```
          - :grok:
                match:
                  message: 'sshd(?:\[%{POSINT:[system][auth][pid]}\])?:'
                add_tag: "i_%{instance_num}"
                break_on_match: 'false'
```
Renders the following configuration:

```
grok {
  add_tag => "i_%{instance_num}"
  break_on_match => "false"
  match => {
    "message" =>  "sshd(?:\\[%{POSINT:[system][auth][pid]}\\])?:"
  }
}
```

Notice the two backlashes in the value of "message" after sshd(?:   
I need just one backslash.

How do I specifiy the message pattern so that it renders this way (with a single backslash) in the configuration file:
```
              sshd(?:\[%{POSINT:[system][auth][pid]}\])?:
```
